[colors.primary]
background = "0x282c34"
foreground = "0xabb2bf"

[colors.normal]
# NOTE: Use "0x131613" for the `black` color if you'd like to see
# black text on the background.
#black = "0x282c34"
black = "0x131613"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0xabb2bf"

[colors.bright]
black = "0x5c6370"
red = "0xe06c75"
green = "0x98c379"
yellow = "0xd19a66"
blue = "0x61afef"
magenta = "0xc678dd"
cyan = "0x56b6c2"
white = "0xffffff"




[font]
size = 12.0

[font.bold]
family = "Ubuntu Mono"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "Ubuntu Mono"
style = "Regular"

[terminal.shell]
program = "/bin/zsh"

[window.padding]
x = 1
y = 1

[terminal]
